### ISSUE TITLE
how to use the plugin?

### ISSUE THREAD

**Issue by yeshiqing** [naoyukik/customize-word-separators-kt-old#1]
I have installed the plugin. I expect it could help me move caret properly among Chinese words. 

~~Could you tell me how to config and use the plugin？~~

![image](https://user-images.githubusercontent.com/11813936/209148637-501514b1-3f1f-496a-b797-68b2d664ac58.png)

![image](https://user-images.githubusercontent.com/11813936/209148882-fe164066-55d3-4b73-b1d6-a3054f7e077b.png)

I copy the regular expressions to the textarea of "Pattern", and trigger the shotcuts of "customize word separators", but there is no effect.

**NOTE for new-comers: this plugin can't support for Chineses words segmentation.**

**Comment by naoyukik** [comment]
@yeshiqing 
I have the full text on the plugin page, but could you use the following setup?
https://plugins.jetbrains.com/plugin/13613-customize-word-separators

Perhaps it will work if you rewrite the `cjk` part to Chinese unicode.
Since `cjk` is for Japanese, you could add it there or rewrite it.
```
cjk, [\u3400-\u9FFF\uF900-\uFAFF]+
hiragana, [\u3040-\u309F]+
katakana, [\u30A1-\u30FA\u30FC-\u30FE]+
kanaSymbol, [\u30A0\u30FB]+
cjkSymbol, [\u2190-\u2193\u25A0\u25A1\u25B2\u25B3\u25BC\u25BD\u25C6\u25C7\u25CB\u25CE\u25CF\u2605\u2606\u3000-\u3020]+
fullDigit, [\uFF10-\uFF19]+
fullLatin, [\uFF21-\uFF3A\uFF41-\uFF5A]+
halfCjkPunctuation, [\uFF61-\uFF65]+
halfKatakana, [\uFF66-\uFF9F]+
......
```

**Comment by yeshiqing** [comment]
@naoyukik  I know the format now, but it has no effect even if the word belongs CJK.

please test the sentence below:
```js
// 㐀㐀㐀㐀㐀㐀㐀㐁㐁㐁㐁|
```

The unicode of word `㐀` is `\u3400`, the `|` means the position of cursor. But when "Move Caret to Prev Word", the cursor come to the beginning of the sentence.

**Comment by naoyukik** [comment]
@yeshiqing 
I Understood.

This plugin moves the cursor for each grouping by `cjk` `hiragana` `katakana` and so on.
It does not stop as long as the characters in the same group are connected.
For example, if you set the following, the cursor should stop at `㐀|㐁`.
```
cjk, [\u3400]+
hiragana, [\u3401]+
```
If the group is composed of identical character types, as in Chinese, it seems difficult to do without using morphological analysis.
This plugin uses regular expressions to separate groups.

**Comment by hogashi** [comment]
@naoyukik I tried to configure at minimum but the cursor doesn't stop on "Move Caret to Next Word" in `xxxaxxx` (I expected it to stop at `x|a` ). Is my config right?

```
a, a+
other, [b-zA-Z0-9]+
```

**Comment by naoyukik** [comment]
@hogashi 
I think it's correct. I checked. Stopped before/after `a`. (`xxx|a|xxx`)
```
a, a+
other, [b-zA-Z0-9]+
```

**Comment by hogashi** [comment]
Thank you @naoyukik , now I got it.  There are two "Move Caret to Next Word" command in the editor now.  I'd been tried the editor native command but I'd had to run one in "Plugins" > "Customize word separators" > "Move Caret to Next Word" and it works!  FYI @yeshiqing 

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/12870472/212064433-2bb45755-86c7-4233-ab0c-ab33bfdf7dcd.png">

@naoyukik BTW, is it the behavior that you expected? I think it would be great if the editor native command overwritten by this plugin to keep keymaps not need to be changed.

**Comment by naoyukik** [comment]
@hogashi Thank you.

This behavior is intended.
I was thinking of overwriting it after releasing version 1.0. Development has stalled...

I was unaware of this because I had removed the native command during development. I guess I didn't explain myself well enough.

**Comment by hogashi** [comment]
@naoyukik That's OK!
I understand the situation ☕ I now realized that migrating the keymaps on "Move Caret to Next Word (with Selection)" is not so hard. And, both commands may be used in the same time to move caret in different purpose (precisely/quickly).
Anyway, it is nice plugin for everyday coding! Thanks 🌟
